Repository Sulagna-Dutta-Roy/Webeginner-projects, pull requests merged in 2022-10, with the labels that each got.

#262 added browser
  Python/Browser/README.md
  Python/Browser/browser.py
Labels: enhancement, SSOC, Beginner

#325 added BFS algo visualizer
  Python/BFS visualizer/BFS algo visualizer.py
  Python/BFS visualizer/Readme.md
  Python/BFS visualizer/output.gif
Labels: enhancement, SSOC, Intermediate

#326 Stripe UI clone
  Stripe Payment Platform UI Clone/README.md
  Stripe Payment Platform UI Clone/images/hero.svg
  Stripe Payment Platform UI Clone/images/logo.svg
  Stripe Payment Platform UI Clone/images/phone.svg
  Stripe Payment Platform UI Clone/images/preview.png
  Stripe Payment Platform UI Clone/index.html
  Stripe Payment Platform UI Clone/scripts/app.js
  Stripe Payment Platform UI Clone/scripts/data.js
  Stripe Payment Platform UI Clone/styles.css
Labels: enhancement, SSOC, Advance

#327 Created a UI only discord clone.
  Discord UI clone/Index.html
  Discord UI clone/Readme.md
  Discord UI clone/assets/images/Discord work.png
  Discord UI clone/assets/images/Discord-logo.png
  Discord UI clone/assets/images/Xbox-discord-logo-image.png
  Discord UI clone/assets/images/background-1-removebg-preview.png
  Discord UI clone/assets/images/background-2-removebg-preview.png
  Discord UI clone/assets/images/background-3-removebg-preview.png
  Discord UI clone/assets/images/discord_white_logo-removebg-preview.png
  Discord UI clone/index.css
Labels: enhancement, SSOC, Intermediate

#328 Drink water
  drinkwater/index.html
  drinkwater/main.js
  drinkwater/style.css
Labels: enhancement, SSOC, Beginner

#329 Agriculture GUI with Databse
  Agriculture Market GUI/CropIcon.png
  Agriculture Market GUI/README.md
  Agriculture Market GUI/main.py
  Agriculture Market GUI/wholesale.sql
Labels: enhancement, SSOC, Intermediate

#315 Added Durga Puja Website
  Durga-puja/Readme.md
  Durga-puja/durga -2.jpg
  Durga-puja/durga-puja.jpg
  Durga-puja/index.html
  Durga-puja/style.css
Labels: enhancement, SSOC, Beginner

#287 Feat 281 added color game using tkinter in python
  Python/Color Game/Readme.md
  Python/Color Game/colorGame.py
  Python/Color Game/screenshot.png
Labels: SSOC, Beginner, Intermediate
