Repository Sulagna-Dutta-Roy/Webeginner-projects, pull requests merged in 2022-08, with the labels that each got.

#73 add background color changer app
  Background Color Changer/css/style.css
  Background Color Changer/images/color_changer.PNG
  Background Color Changer/index.html
  Background Color Changer/js/script.js
  Background Color Changer/readme.md
Labels: enhancement, SSOC, Beginner

#70 Online Calculator
  Online Calculator/README.md
  Online Calculator/index.html
  Online Calculator/preview.png
  Online Calculator/src/index.css
  Online Calculator/src/index.js
Labels: enhancement, SSOC, Beginner

#98 added face recognition + filter
  Python/filters/.idea/.gitignore
  Python/filters/.idea/.name
  Python/filters/.idea/filter.iml
  Python/filters/.idea/inspectionProfiles/Project_Default.xml
  Python/filters/.idea/inspectionProfiles/profiles_settings.xml
  Python/filters/.idea/misc.xml
  Python/filters/.idea/modules.xml
  Python/filters/README.md
  Python/filters/beard.png
  Python/filters/cool.png
  Python/filters/haarcascade_frontalface_default.xml
  Python/filters/main.py
  Python/filters/native.png
  Python/filters/pirate.png
  Python/filters/star.png
  Python/filters/sunglass.png
Labels: enhancement, SSOC, Intermediate

#99 Image to pdf
  Python/png or jpeg to pdf/.idea/.gitignore
  Python/png or jpeg to pdf/.idea/inspectionProfiles/Project_Default.xml
  Python/png or jpeg to pdf/.idea/inspectionProfiles/profiles_settings.xml
  Python/png or jpeg to pdf/.idea/misc.xml
  Python/png or jpeg to pdf/.idea/modules.xml
  Python/png or jpeg to pdf/.idea/png or jpeg to pdf.iml
  Python/png or jpeg to pdf/README.md
  Python/png or jpeg to pdf/main.py
Labels: enhancement, SSOC, Beginner

#83 # 21 Dice-Game Added
  Dice-Game/README.md
  Dice-Game/images/dice1.png
  Dice-Game/images/dice2.png
  Dice-Game/images/dice3.png
  Dice-Game/images/dice4.png
  Dice-Game/images/dice5.png
  Dice-Game/images/dice6.png
  Dice-Game/index.html
  Dice-Game/index.js
  Dice-Game/readme-img/Pic_1.png
  Dice-Game/readme-img/Pic_2.png
  Dice-Game/readme-img/Pic_3.png
  Dice-Game/styles.css
Labels: enhancement, SSOC, Intermediate

#54 TicTacToe
  Python/Tic Tac Toe/README.md
  Python/Tic Tac Toe/TicTacToe.py
Labels: enhancement, SSOC, Intermediate

#115 Slide share to pdf
  Python/SlideShare to PDF/README.md
  Python/SlideShare to PDF/SlideShare.py
Labels: enhancement, SSOC, Beginner

#135 Qr Generator Added
  QR Generator/README.md
  QR Generator/index.html
  QR Generator/style.css
Labels: enhancement, SSOC, Beginner

#151 Currency Convertor Added [SSOC'22]
  currency convertor/index.html
  currency convertor/js/country.js
  currency convertor/js/index.js
  currency convertor/readme.md
  currency convertor/style.css
Labels: enhancement, SSOC, Beginner

#100 Two step Form
  Two step Form/README.md
  Two step Form/index.html
  Two step Form/preview.png
  Two step Form/validate.js
Labels: enhancement, SSOC, Beginner

#164 WHAC - A - MOLE FILES ADDED
  WHAC-A-MOLE/Preview.png
  WHAC-A-MOLE/README.md
  WHAC-A-MOLE/app.js
  WHAC-A-MOLE/index.html
  WHAC-A-MOLE/mole.jpg
  WHAC-A-MOLE/styles.css
Labels: enhancement, SSOC, Intermediate

#132 Added a Readme to CSS Loaders
  Css Loaders/README.md
  Css Loaders/loaders.png
Labels: enhancement, SSOC, Beginner

#168 Contact Form - UI Design
  Contact Form - UI Design/README.md
  Contact Form - UI Design/form.css
  Contact Form - UI Design/index.html
  Contact Form - UI Design/preview.png
Labels: enhancement, SSOC, Beginner

#162 Weather App using js
  Weather App in JavaScript/README.md
  Weather App in JavaScript/Screenshot1.png
  Weather App in JavaScript/Screenshot2.png
  Weather App in JavaScript/icons/clear.svg
  Weather App in JavaScript/icons/cloud.svg
  Weather App in JavaScript/icons/haze.svg
  Weather App in JavaScript/icons/rain.svg
  Weather App in JavaScript/icons/snow.svg
  Weather App in JavaScript/icons/storm.svg
  Weather App in JavaScript/index.html
  Weather App in JavaScript/script.js
  Weather App in JavaScript/style.css
Labels: enhancement, SSOC, Intermediate

#161 Added Facebook Login Clone code
  Facebook Login/Readme.md
  Facebook Login/assets/index.b73823d5.css
  Facebook Login/assets/logo.9531e960.svg
  Facebook Login/index.html
Labels: enhancement, SSOC, Beginner

#158 Created Dynamic Table project
  Dynamic Table/index.html
  Dynamic Table/readme.md
  Dynamic Table/readmeimage.png
  Dynamic Table/script.js
  Dynamic Table/style.css
Labels: enhancement, SSOC, Beginner

#167 Testimonial page
  Testimonial page/README.md
  Testimonial page/assets/image_2022-08-16_235957250.png
  Testimonial page/assets/img1.jpg
  Testimonial page/assets/img2.jpg
  Testimonial page/assets/img3.jpg
  Testimonial page/index.css
  Testimonial page/index.html
Labels: enhancement, SSOC, Beginner

#138 Tribute Page project
  Tribute-Page/images/elon-b.png
  Tribute-Page/images/elon-h.png
  Tribute-Page/images/elon-s.png
  Tribute-Page/images/elon-t.png
  Tribute-Page/images/ss of project.png
  Tribute-Page/index.html
  Tribute-Page/readme.md
  Tribute-Page/style.css
Labels: enhancement, SSOC, Beginner

#137 Solved issue #123 | Bug Fix | Added extra Functionality
  digital clock/README.md
  digital clock/index.html
Labels: bug, enhancement, SSOC, Beginner

#108 Drawingboard
  DrawingBoard/README.md
  DrawingBoard/css/styles.css
  DrawingBoard/css/whiteboard.css
  DrawingBoard/index.html
  DrawingBoard/js/script.js
  DrawingBoard/preview.png
Labels: enhancement, SSOC, Intermediate

#92 Candy Museum
  Candy Museum/README.md
  Candy Museum/images/gumball.png
  Candy Museum/images/hand2.png
  Candy Museum/images/lolli_icon.png
  Candy Museum/images/milk.png
  Candy Museum/images/preview.jpeg
  Candy Museum/images/sprinkles.png
  Candy Museum/index.html
  Candy Museum/style.css
Labels: enhancement, SSOC, Beginner

#133 User can see number of tries in Number Guessing Game
  Number Guessing Game/index.html
  Number Guessing Game/index.js
  Number Guessing Game/style.css
Labels: enhancement, SSOC, Beginner

#116 Text editor
  Python/Text Editor/README.md
  Python/Text Editor/TextEditor.py
Labels: enhancement, SSOC, Intermediate

#107 New Year counter web app
  Python/newYearCounter/countDown/Readme.md
  Python/newYearCounter/countDown/__init__.py
  Python/newYearCounter/countDown/apps.py
  Python/newYearCounter/countDown/static/countDown/styles.css
  Python/newYearCounter/countDown/templates/countDown/index.html
  Python/newYearCounter/countDown/urls.py
  Python/newYearCounter/countDown/views.py
  Python/newYearCounter/manage.py
  Python/newYearCounter/newYearCounter/__init__.py
  Python/newYearCounter/newYearCounter/asgi.py
  Python/newYearCounter/newYearCounter/settings.py
  Python/newYearCounter/newYearCounter/urls.py
  Python/newYearCounter/newYearCounter/wsgi.py
  Python/newYearCounter/requirements.txt
Labels: enhancement, SSOC, Beginner

#172 Enhanced UI
  Stopwatch App/assets/css/style.css
  Stopwatch App/index.html
Labels: enhancement, SSOC, Beginner

#185 Exploratory Data analysis (Spotify)
  Python/Exploratory data analysis using python/README.md
  Python/Exploratory data analysis using python/exploratory data analysis using python.ipynb
Labels: enhancement, SSOC, Intermediate

#188 Gym Dashboard
  Gym Website/38464.png
  Gym Website/README.md
  Gym Website/Workout.jpg
  Gym Website/index.html
Labels: enhancement, SSOC, Beginner

#149 Indian Flag added
  Python/National Flag/IndianFlag.py
  Python/National Flag/README.md
Labels: enhancement, SSOC, Beginner

#144 Movie searching app
  Movie searching app/README.md
  Movie searching app/images/app_preview.png
  Movie searching app/index.html
  Movie searching app/scripts/script.js
  Movie searching app/styles/style.css
Labels: enhancement, SSOC, Intermediate

#91 Message Encoder and Decoder
  Python/Message Encoder and Decoder/README.md
  Python/Message Encoder and Decoder/app.py
Labels: enhancement, SSOC, Intermediate

#191 Customization || Enhancement || Random Password Generator
  Random Password Generator/Readme.md
  Random Password Generator/index.html
  Random Password Generator/main.js
  Random Password Generator/style.css
Labels: enhancement, SSOC, Beginner

#178 Animated Carousel #178
  Animated Carousel/README.md
  Animated Carousel/assets/image-1.jpg
  Animated Carousel/assets/image-1.webp
  Animated Carousel/assets/image-2.jpg
  Animated Carousel/assets/image-3.jpg
  Animated Carousel/assets/image-4.jpg
  Animated Carousel/assets/image-5.jfif
  Animated Carousel/bootstrap.min.css
  Animated Carousel/bootstrap.min.js
  Animated Carousel/docs.min.js
  Animated Carousel/ie10-viewport-bug-workaround.js
  Animated Carousel/index.html
  Animated Carousel/js/jquery-3.4.1.min.js
  Animated Carousel/js/jssor.slider.min.js
  Responsive Card Design/index.html
  Responsive Card Design/style.css
Labels: enhancement, SSOC, Beginner

#147 Added the Dino game.
  A dino game/Images/51955.jpg
  A dino game/Images/Landing page.png
  A dino game/Images/background2.jpg
  A dino game/Images/cactus3.png.png
  A dino game/Images/dino1.png
  A dino game/Images/game page.png
  A dino game/LandingPage.css
  A dino game/LandingPage.html
  A dino game/Readme.md
  A dino game/dino.css
  A dino game/dino.html
  A dino game/dino.js
Labels: enhancement, SSOC, Intermediate

#198 QR Code Generator using Python
  Python/QR Code Generator/README.md
  Python/QR Code Generator/code.py
  Python/QR Code Generator/myqr.png
Labels: enhancement, SSOC, Beginner

#203 Random Password Generator using Python
  Python/Random Password Generator/ Random Password Generator.py
  Python/Random Password Generator/README.md
Labels: enhancement, SSOC, Beginner

#204 updated UI and added new features.
  Stopwatch App/README.md
  Stopwatch App/index.html
  Stopwatch App/script/script.js
Labels: documentation, enhancement, SSOC, Beginner

#190 Random Recipe Generator
  Random_Recipe_Generator/README.md
  Random_Recipe_Generator/index.html
  Random_Recipe_Generator/index.js
  Random_Recipe_Generator/styles.css
Labels: enhancement, SSOC, Beginner

#200 Link Tree Template added
  Link Tree template/Index.html
  Link Tree template/README.md
  Link Tree template/bg3.jpg
  Link Tree template/favicon.jpg
  Link Tree template/style.css
  Link Tree template/th.webp
Labels: enhancement, SSOC, Beginner

#201 Added more CSS loaders.
  Css Loaders/Style.css
  Css Loaders/index.html
  Css Loaders/loaders.png
Labels: enhancement, SSOC, Beginner

#212 Piano Kit
  js-piano/index.html
  js-piano/index.js
  js-piano/keys/key01.mp3
  js-piano/keys/key02.mp3
  js-piano/keys/key03.mp3
  js-piano/keys/key04.mp3
  js-piano/keys/key05.mp3
  js-piano/keys/key06.mp3
  js-piano/keys/key07.mp3
  js-piano/keys/key08.mp3
  js-piano/keys/key09.mp3
  js-piano/keys/key10.mp3
  js-piano/keys/key11.mp3
  js-piano/keys/key12.mp3
  js-piano/keys/key13.mp3
  js-piano/keys/key14.mp3
  js-piano/keys/key15.mp3
  js-piano/keys/key16.mp3
  js-piano/keys/key17.mp3
  js-piano/keys/key18.mp3
  js-piano/keys/key19.mp3
  js-piano/keys/key20.mp3
  js-piano/keys/key21.mp3
  js-piano/keys/key22.mp3
  js-piano/keys/key23.mp3
  js-piano/keys/key24.mp3
  js-piano/readme.md
  js-piano/screenshot/piano.png
  js-piano/styles.css
Labels: enhancement, SSOC, Beginner

#226 Better UI
  Image Gallery/README.md
  Image Gallery/images/fim.png
  Image Gallery/style.css
Labels: documentation, enhancement, SSOC, Beginner

#222 Responsive Card Design
  Responsive Card Design/README.md
  Responsive Card Design/assets/demo.jpg
  Responsive Card Design/index.html
  Responsive Card Design/style.css
Labels: enhancement, SSOC, Beginner

#219 Text to speech
  Python/Text to Speech/README.md
  Python/Text to Speech/text_to_speech.py
  Python/Text to Speech/text_to_speech.wav
  Python/Text to Speech/texttospeech.txt
Labels: enhancement, SSOC, Beginner

#225 Login Page UI
  Login Page UI/README.md
  Login Page UI/index.html
  Login Page UI/style.css
Labels: enhancement, SSOC, Beginner

#231 Added prefix and postfix expression calculator
  Prefix-Postfix-Calculator/README.md
  Prefix-Postfix-Calculator/assets/Images/landing page.png
  Prefix-Postfix-Calculator/assets/Images/postfix.png
  Prefix-Postfix-Calculator/assets/Images/prefix.png
  Prefix-Postfix-Calculator/assets/Images/result.png
  Prefix-Postfix-Calculator/assets/css/landingpage.css
  Prefix-Postfix-Calculator/assets/css/postfix.css
  Prefix-Postfix-Calculator/assets/css/prefix.css
  Prefix-Postfix-Calculator/assets/js/postfix.js
  Prefix-Postfix-Calculator/assets/js/prefix.js
  Prefix-Postfix-Calculator/index.html
  Prefix-Postfix-Calculator/postfix.html
  Prefix-Postfix-Calculator/prefix.html
Labels: enhancement, SSOC, Beginner

#224 youtube video downloader
  Python/Youtube-video-downloader/.idea/.gitignore
  Python/Youtube-video-downloader/.idea/inspectionProfiles/Project_Default.xml
  Python/Youtube-video-downloader/.idea/inspectionProfiles/profiles_settings.xml
  Python/Youtube-video-downloader/.idea/misc.xml
  Python/Youtube-video-downloader/.idea/modules.xml
  Python/Youtube-video-downloader/.idea/yt do.iml
  Python/Youtube-video-downloader/README.md
  Python/Youtube-video-downloader/youtube-video-downloader.py
Labels: enhancement, SSOC, Intermediate

#223 Exploratory data analysis (covid-19)
  Python/Exploratory data analysis 1/Covid_19_EDA1.ipynb
  Python/Exploratory data analysis 1/README.md
Labels: enhancement, SSOC, Intermediate

#207 Added Educational website
  Education website/CSS/style1.css
  Education website/about.html
  Education website/ai.html
  Education website/blockchain.html
  Education website/contact.html
  Education website/css.html
  Education website/dbms.html
  Education website/ds.html
  Education website/dsa.html
  Education website/game.html
  Education website/homepage2.html
  Education website/mobile.html
  Education website/readme.md
  Education website/robotics.html
  Education website/skills.html
  Education website/web-development.html
Labels: enhancement, SSOC, Beginner

#227 Updated with additional functionalities
  Rocket Attack Game/README.md
  Rocket Attack Game/Rocket_Attack_Game.py
Labels: enhancement, SSOC, Beginner

#74 I have modified the html and css files of simple registration form
  Simple Registration Form/Images/Output.PNG
  Simple Registration Form/Images/background-image.png
  Simple Registration Form/Images/favicon.ico
  Simple Registration Form/README.md
  Simple Registration Form/index.html
  Simple Registration Form/index.js
  Simple Registration Form/style.css
Labels: enhancement, SSOC, Beginner

#229 Snake game
  Python/Snake Game/Assets/snake demo.png
  Python/Snake Game/Readme.md
  Python/Snake Game/food.py
  Python/Snake Game/main.py
  Python/Snake Game/scoreboard.py
  Python/Snake Game/snake.py
  Python/Snake Game/yumm.py
Labels: enhancement, SSOC, Beginner

#176 Restaurant Management System
  Python/Restaurant Management/Readme.md
  Python/Restaurant Management/Restaurant-System.py
Labels: enhancement, SSOC, Beginner

#238 Age Calculator
  Age Calculator/Age.html
  Age Calculator/Age.js
  Age Calculator/README.md
  Age Calculator/Screenshot 2022-08-28 211519.png
  Age Calculator/Style.css
Labels: enhancement, SSOC, Beginner

#208 Blog_Website
  Blog Website/README.md
  Blog Website/home.html
  Blog Website/images/banner.png
  Blog Website/images/card1.png
  Blog Website/images/card2.png
  Blog Website/images/card3.png
  Blog Website/images/hero.png
  Blog Website/images/long-big-card.png
  Blog Website/images/long-card.png
  Blog Website/post.html
  Blog Website/previewBlog.png
  Blog Website/style.css
Labels: enhancement, SSOC, Beginner
