Repository Sulagna-Dutta-Roy/Webeginner-projects, pull requests merged in 2022-09, with the labels that each got.

#119 Duplicate file remover
  Python/Duplicate File Remover/DuplicateFileRemover.py
  Python/Duplicate File Remover/README.md
Labels: enhancement, SSOC, Intermediate

#244 Enhanced UI of Currency convertor
  currency convertor/backg.png
  currency convertor/style.css
Labels: enhancement, SSOC, Beginner

#109 Added Rock-Paper-Scissor game using python
  Python/Rock-Paper-Scissor/Readme.md
  Python/Rock-Paper-Scissor/Rock-Paper-Scissor.py
  Python/Rock-Paper-Scissor/screenshot.png
Labels: enhancement, SSOC, Intermediate

#248 Adding quiz web app using js
  Quiz-App/README.md
  Quiz-App/index.html
  Quiz-App/script.js
  Quiz-App/ss1.png
  Quiz-App/ss2.png
  Quiz-App/style.css
Labels: enhancement, SSOC, Intermediate

#250 Movie ticket booking GUI with database
  Movie Ticket Booking/Movie Database GUI.py
  Movie Ticket Booking/README.md
  Movie Ticket Booking/movie.sql
  Movie Ticket Booking/movieIcon.png
Labels: enhancement, SSOC, Advance

#247 Made the images visible in Candy Museum
  Candy Museum/index.html
  Candy Museum/style.css
Labels: bug, enhancement, SSOC

#192 Ice_cream website
  ice_cream/icecream.html
  ice_cream/images/choclateicecream.webp
  ice_cream/images/cone.webp
  ice_cream/images/coold.webp
  ice_cream/images/cupPacking.webp
  ice_cream/images/scoops.webp
  ice_cream/images/strawberry.webp
  ice_cream/images/tasty-tiramisu-dessert-white-background_681987-3086.webp
Labels: enhancement, SSOC, Beginner

#258 Character counter
  character counter/index.html
  character counter/index.js
  character counter/style.css
  wordler/assets/css/style.css
  wordler/assets/img/icons/android-icon-144x144.png
  wordler/assets/img/icons/android-icon-192x192.png
  wordler/assets/img/icons/android-icon-36x36.png
  wordler/assets/img/icons/android-icon-48x48.png
  wordler/assets/img/icons/android-icon-72x72.png
  wordler/assets/img/icons/android-icon-96x96.png
  wordler/assets/img/icons/apple-icon-114x114.png
  wordler/assets/img/icons/apple-icon-120x120.png
  wordler/assets/img/icons/apple-icon-144x144.png
  wordler/assets/img/icons/apple-icon-152x152.png
  wordler/assets/img/icons/apple-icon-180x180.png
  wordler/assets/img/icons/apple-icon-57x57.png
  wordler/assets/img/icons/apple-icon-60x60.png
  wordler/assets/img/icons/apple-icon-72x72.png
  wordler/assets/img/icons/apple-icon-76x76.png
  wordler/assets/img/icons/apple-icon-precomposed.png
  wordler/assets/img/icons/apple-icon.png
  wordler/assets/img/icons/browserconfig.xml
  wordler/assets/img/icons/favicon-16x16.png
  wordler/assets/img/icons/favicon-32x32.png
  wordler/assets/img/icons/favicon-96x96.png
  wordler/assets/img/icons/favicon.ico
  wordler/assets/img/icons/manifest.json
  wordler/assets/img/icons/ms-icon-144x144.png
  wordler/assets/img/icons/ms-icon-150x150.png
  wordler/assets/img/icons/ms-icon-310x310.png
  wordler/assets/img/icons/ms-icon-70x70.png
  wordler/assets/img/screenshots/difficult mode.png
  wordler/assets/img/screenshots/difficulty select.png
  wordler/assets/img/screenshots/game board.png
  wordler/assets/img/screenshots/give up screen.png
  wordler/assets/img/screenshots/help game.png
  wordler/assets/img/screenshots/help options.png
  wordler/assets/img/screenshots/in game difficulty select.png
  wordler/assets/img/screenshots/in game level select.png
  wordler/assets/img/screenshots/level select.png
  wordler/assets/img/screenshots/lost screen.png
  wordler/assets/img/screenshots/menu.png
  wordler/assets/img/screenshots/score easy.png
  wordler/assets/img/screenshots/streak easy.png
  wordler/assets/img/screenshots/win screen.png
  wordler/assets/img/social/facebook_icon.png
  wordler/assets/img/social/reddit_icon.png
  wordler/assets/img/social/telegram_icon.png
  wordler/assets/img/social/twitter_icon.png
  wordler/assets/js/game.js
  wordler/assets/js/words/3.js
  wordler/assets/js/words/4.js
  wordler/assets/js/words/5.js
  wordler/index.html
Labels: enhancement, SSOC, Intermediate

#254 Resume builder Web app added
  Resume-Generator/README.md
  Resume-Generator/index.html
  Resume-Generator/script.js
  Resume-Generator/ss.png
  Resume-Generator/ss2.png
  Resume-Generator/style.css
Labels: enhancement, SSOC, Advance

#259 Added google keep clone project
  Google Keep Clone/README.md
  Google Keep Clone/assets/Images/google keep icon.png
  Google Keep Clone/assets/Images/google keep.png
  Google Keep Clone/assets/Images/keeps icon.png
  Google Keep Clone/assets/Images/user.png
  Google Keep Clone/googlekeep.css
  Google Keep Clone/index.html
Labels: enhancement, SSOC, Intermediate

#271 portfolio
  Portfolio/README.md
  Portfolio/images/C (1).png
  Portfolio/images/PHP.png
  Portfolio/images/PYTHON.png
  Portfolio/images/about-us.jpg
  Portfolio/images/about.jpg
  Portfolio/images/avatar.png
  Portfolio/images/bg.gif
  Portfolio/images/bootstrap.png
  Portfolio/images/css-3.png
  Portfolio/images/db.png
  Portfolio/images/git-logo.png
  Portfolio/images/html.png
  Portfolio/images/js.png
  Portfolio/images/node.jpeg
  Portfolio/images/project.jpg
  Portfolio/images/projectmanager.png
  Portfolio/images/react.png
  Portfolio/images/shape.png
  Portfolio/images/sql.png
  Portfolio/index.html
  Portfolio/screenshotss.png
  Portfolio/style.css
Labels: enhancement, SSOC, Beginner

#266 Donation Website
  Donation Website/Readme.md
  Donation Website/about.html
  Donation Website/causes.html
  Donation Website/contact.html
  Donation Website/css/about.css
  Donation Website/css/bootstrap.min.css
  Donation Website/css/causes.css
  Donation Website/css/contact.css
  Donation Website/css/donate.css
  Donation Website/css/events.css
  Donation Website/css/owl.carousel.min.css
  Donation Website/css/styles.css
  Donation Website/donate.html
  Donation Website/events.html
  Donation Website/img/about.jpg
  Donation Website/img/carousel-1.jpg
  Donation Website/img/carousel-2.jpg
  Donation Website/img/carousel-3.jpg
  Donation Website/img/causes-1.jpg
  Donation Website/img/causes-2.jpg
  Donation Website/img/causes-3.jpg
  Donation Website/img/causes-4.jpg
  Donation Website/img/contact.jpg
  Donation Website/img/donate.jpg
  Donation Website/img/event-1.jpg
  Donation Website/img/event-2.jpg
  Donation Website/img/facts.jpg
  Donation Website/img/page-header.jpg
  Donation Website/img/volunteer.jpg
  Donation Website/index.html
  Donation Website/js/bootstrap.bundle.min.js
  Donation Website/js/bootstrap.min.js
  Donation Website/js/jquery.js
  Donation Website/js/owl.carousel.min.js
  Donation Website/js/script.js
Labels: enhancement, SSOC, Beginner

#263 added weather-teller
  Python/Weather-teller/.idea/.gitignore
  Python/Weather-teller/.idea/inspectionProfiles/Project_Default.xml
  Python/Weather-teller/.idea/inspectionProfiles/profiles_settings.xml
  Python/Weather-teller/.idea/misc.xml
  Python/Weather-teller/.idea/modules.xml
  Python/Weather-teller/.idea/project dev.iml
  Python/Weather-teller/README.md
  Python/Weather-teller/main.py
Labels: enhancement, SSOC, Beginner

#260 Todo List
  Todo List/README.md
  Todo List/assets/github.png
  Todo List/assets/main.js
  Todo List/assets/style.css
  Todo List/index.html
Labels: enhancement, SSOC, Intermediate

#236 Number Guessing Game
  Python/Number Guessing Game/num_guessing_game.py
  Python/Number Guessing Game/readme.md
Labels: enhancement, SSOC, Beginner

#272 Chatbot using JavaScript
  Chatbot/README.md
  Chatbot/index.html
  Chatbot/script.js
  Chatbot/style.css
Labels: enhancement, SSOC, Beginner

#283 Amazon prime video login page clone
  Amazon Prime Login/README.md
  Amazon Prime Login/Screenshot 2022-09-19 155954.png
  Amazon Prime Login/amazon1.png
  Amazon Prime Login/index.css
  Amazon Prime Login/index.html
  Amazon Prime Login/index.js
  Amazon Prime Login/primelogo.png
Labels: enhancement, SSOC, Beginner

#278 Flappy Bird clone
  Flappy Bird Clone/Flappy_bird.py
  Flappy Bird Clone/README.md
  Flappy Bird Clone/gallery/audio/die.wav
  Flappy Bird Clone/gallery/audio/hit.wav
  Flappy Bird Clone/gallery/audio/point.wav
  Flappy Bird Clone/gallery/audio/swoosh.wav
  Flappy Bird Clone/gallery/audio/wing.wav
  Flappy Bird Clone/gallery/sprites/0.png
  Flappy Bird Clone/gallery/sprites/1.png
  Flappy Bird Clone/gallery/sprites/2.png
  Flappy Bird Clone/gallery/sprites/3.png
  Flappy Bird Clone/gallery/sprites/4.png
  Flappy Bird Clone/gallery/sprites/5.png
  Flappy Bird Clone/gallery/sprites/6.png
  Flappy Bird Clone/gallery/sprites/7.png
  Flappy Bird Clone/gallery/sprites/8.png
  Flappy Bird Clone/gallery/sprites/9.png
  Flappy Bird Clone/gallery/sprites/background.png
  Flappy Bird Clone/gallery/sprites/base.png
  Flappy Bird Clone/gallery/sprites/bird.png
  Flappy Bird Clone/gallery/sprites/flappy_pic.png
  Flappy Bird Clone/gallery/sprites/flappy_pic2.png
  Flappy Bird Clone/gallery/sprites/message.png
  Flappy Bird Clone/gallery/sprites/pipe.png
Labels: enhancement, SSOC, Intermediate

#264 Creating weight convertor on planets
  Weight on differen planets/README.md
  Weight on differen planets/images/Earth.png
  Weight on differen planets/images/Jupiter.png
  Weight on differen planets/images/Mars.png
  Weight on differen planets/images/Mercury.png
  Weight on differen planets/images/Neptune.png
  Weight on differen planets/images/Saturn.png
  Weight on differen planets/images/Space.jpg
  Weight on differen planets/images/Uranus.png
  Weight on differen planets/images/Venus.png
  Weight on differen planets/index.html
  Weight on differen planets/script.js
  Weight on differen planets/style.css
Labels: enhancement, SSOC, Beginner

#296 Title:Exploratory data analysis using student dataset
  Python/Eda  student/README.md
  Python/Eda  student/student_project (1).ipynb
Labels: enhancement, SSOC, Intermediate

#275 Feat-274-registrationForm
  registration template/Readme.md
  registration template/index.html
  registration template/style.css
Labels: enhancement, SSOC, Beginner

#270 Url shortener
  Python/URL - Shortener/readme.md
  Python/URL - Shortener/url-shortener.py
Labels: enhancement, SSOC, Beginner

#300 Fav recipe
  Recipe_Search/Readme.md
  Recipe_Search/index.html
  Recipe_Search/index.js
  Recipe_Search/style.css
Labels: enhancement, SSOC, Intermediate

#306 Improves the productivity || Added icon
  Age Calculator/Age.html
  Age Calculator/Age.js
  Age Calculator/README.md
  Age Calculator/icons8-puzzle-16.png
Labels: bug, enhancement, SSOC

#302 Improved UI of Number Guessing Game
  Number Guessing Game/index.html
  Number Guessing Game/index.js
  Number Guessing Game/numbers.png
  Number Guessing Game/readme.md
  Number Guessing Game/style.css
Labels: documentation, enhancement, SSOC

#310 Digital whiteboard
  Python/Digital Whiteboard/README.md
  Python/Digital Whiteboard/board.py
  Python/Digital Whiteboard/images/board2_ss.png
  Python/Digital Whiteboard/images/board_ss.png
  Python/Digital Whiteboard/images/color_section.png
  Python/Digital Whiteboard/images/eraser.png
  Python/Digital Whiteboard/images/logo.png
Labels: enhancement, SSOC, Beginner

#316 Payment Gateway Integration Website
  Payment Website/README.md
  Payment Website/index.html
  Payment Website/style.css
Labels: enhancement, SSOC, Intermediate

#320 Spelling Checker
  Python/Spelling Checker/README.md
  Python/Spelling Checker/check_img.png
  Python/Spelling Checker/spell_check.py
Labels: enhancement, SSOC, Beginner
